name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Write service account key file
        shell: bash
        run: |
          printf '%s' "${{ secrets.SERVICE_ACCOUNT_JSON }}" > service-account.json

      - name: Validate service-account.json
        shell: bash
        run: |
          head -n1 service-account.json | grep -q '^{\"' \
            && echo "service-account.json is valid JSON" \
            || (echo "ERROR: invalid JSON" >&2 && exit 1)

      - name: Run MinersUnion parser
        env:
          SERVICE_ACCOUNT_JSON: service-account.json
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
        run: |
          python minersunion-parser.py
