name: CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # путь к файлу, в который мы распишем JSON
      GOOGLE_APPLICATION_CREDENTIALS: service-account.json
      SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Dump service account JSON
        shell: bash
        run: |
          # записываем секрет, который хранит чистый JSON
          printf '%s\n' "${{ secrets.SERVICE_ACCOUNT_JSON }}" > service-account.json

      - name: Validate service-account.json
        shell: bash
        run: |
          if ! head -n1 service-account.json | grep -q '{'; then
            echo "ERROR: service-account.json doesn't start with '{'—проверьте секрет SERVICE_ACCOUNT_JSON" >&2
            exit 1
          fi

      - name: Run MinersUnion parser
        run: |
          python minersunion-parser.py
