# .github/workflows/ci.yml

name: CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Write service account key file
        shell: bash
        run: |
          # Записываем содержимое секрета SERVICE_ACCOUNT_JSON в файл
          printf '%s\n' "${{ secrets.SERVICE_ACCOUNT_JSON }}" > service-account.json

      - name: Validate JSON structure
        shell: bash
        run: |
          # Быстрая проверка начала файла
          head -n1 service-account.json | grep -q '^{\"' \
            && echo "service-account.json looks valid" \
            || (echo "ERROR: invalid JSON" >&2 && exit 1)

      - name: Run MinersUnion parser
        env:
          GOOGLE_APPLICATION_CREDENTIALS: service-account.json
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
        run: |
          python minersunion-parser.py
